"use client";
import { useState, useEffect, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { apiRequest } from '@/lib/api';
import UniversityCard from '@/components/UniversityCard';

interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

interface Task {
  id: number;
  title: string;
  is_completed: boolean;
}

export default function Dashboard() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [stage, setStage] = useState('LOADING...');
  const [isTyping, setIsTyping] = useState(false);
  const [shortlist, setShortlist] = useState<any[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]); 
  const scrollRef = useRef<HTMLDivElement>(null);
  const router = useRouter();

  const syncChatAndStatus = useCallback(async () => {
    try {
      // Fetch Chat History
      const history = await apiRequest('/ai/history');
      setMessages(history.length > 0 ? history : [{ role: 'assistant', content: "Hello! Ready to explore your 20 university options?" }]);

      // Fetch User Profile, Shortlist, and Tasks
      const userData = await apiRequest('/user/me');
      setStage(userData.current_stage);
      setShortlist(userData.shortlisted_universities || []);
      setTasks(userData.tasks || []); 
    } catch (err) {
      console.error("Sync failed");
    }
  }, []);

  // FIXED: Single declaration of toggleTask
  const toggleTask = async (taskId: number) => {
    try {
      await apiRequest(`/user/tasks/${taskId}/toggle`, {
        method: 'POST'
      });
      // Refresh the dashboard data to show the updated task state
      syncChatAndStatus();
    } catch (err) {
      console.error("Failed to toggle task status");
    }
  };

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
      router.push('/login');
      return;
    }
    syncChatAndStatus();
  }, [router, syncChatAndStatus]);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages, isTyping]);

  const onSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isTyping) return;

    setMessages(prev => [...prev, { role: 'user', content: input }]);
    const currentInput = input;
    setInput('');
    setIsTyping(true);

    try {
      const data = await apiRequest('/ai/chat', {
        method: 'POST',
        body: JSON.stringify({ message: currentInput }),
      });
      setMessages(prev => [...prev, { role: 'assistant', content: data.response }]);
      if (data.next_stage) setStage(data.next_stage);
      
      // Refresh status to catch any new tasks generated by the AI response
      syncChatAndStatus();
    } catch (err: any) {
      setMessages(prev => [...prev, { role: 'system', content: err.message }]);
    } finally {
      setIsTyping(false);
    }
  };

  const handleRemoveFromShortlist = async (uniId: number) => {
    try {
      await apiRequest(`/user/shortlist/${uniId}`, { method: 'POST' });
      syncChatAndStatus();
    } catch (err) {
      console.error("Removal failed");
    }
  };

  return (
    <div className="flex h-screen bg-slate-950 text-slate-200">
      {/* Sidebar */}
      <div className="w-80 border-r border-slate-800 bg-slate-900 p-6 flex flex-col overflow-y-auto">
        <div className="flex items-center gap-2 mb-8">
          <div className="w-3 h-3 bg-blue-500 rounded-full animate-pulse"></div>
          <h1 className="text-2xl font-bold text-blue-400">Counsellor</h1>
        </div>

        {/* Navigation */}
        <div className="flex flex-col gap-3 mb-8">
          <button onClick={() => router.push('/discovery')} className="w-full py-3 bg-blue-600/10 hover:bg-blue-600/20 border border-blue-500/30 text-blue-400 rounded-xl font-bold transition-all flex items-center justify-center gap-2 group">
            <span>Explore Universities</span>
            <span className="group-hover:translate-x-1 transition-transform">→</span>
          </button>
          <button onClick={() => router.push('/locker')} className="w-full py-3 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-300 rounded-xl font-bold transition-all flex items-center justify-center gap-2">
            <span>SOP Locker</span>
            <span className="text-lg">📁</span>
          </button>
        </div>
        
        {/* Stage Indicator */}
        <div className="mb-8">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-2 ml-1">Current Stage</p>
          <div className="rounded-xl bg-slate-800 p-4 border border-blue-500/10 uppercase text-xs font-bold text-blue-300">
            {stage.replace(/_/g, ' ')}
          </div>
        </div>

        {/* AI To-Do List */}
        <div className="mb-8">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-4 ml-1">AI To-Do List</p>
          <div className="space-y-2">
            {tasks.length > 0 ? tasks.map(task => (
              <div key={task.id} className="flex items-center gap-3 bg-slate-800/50 p-3 rounded-xl border border-slate-700/50">
                <input 
                  type="checkbox" 
                  checked={task.is_completed}
                  onChange={() => toggleTask(task.id)}
                  className="w-4 h-4 rounded border-slate-700 bg-slate-900 text-blue-600 focus:ring-0 cursor-pointer"
                />
                <span className={`text-[11px] ${task.is_completed ? 'line-through text-slate-600' : 'text-slate-300'}`}>
                  {task.title}
                </span>
              </div>
            )) : (
              <p className="text-[10px] text-slate-600 italic ml-1">No tasks generated yet.</p>
            )}
          </div>
        </div>

        {/* Shortlist */}
        <div className="flex-1">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-4 ml-1">Shortlist ({shortlist.length})</p>
          <div className="space-y-4">
            {shortlist.length > 0 ? (
              shortlist.map(uni => (
                <div key={uni.id} className="relative group">
                  <UniversityCard uni={uni} />
                  <button onClick={() => handleRemoveFromShortlist(uni.id)} className="absolute -top-1 -right-1 bg-red-500 text-white w-5 h-5 rounded-full text-xs flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity shadow-lg z-20">×</button>
                </div>
              ))
            ) : (
              <div className="text-center py-8 border-2 border-dashed border-slate-800 rounded-2xl">
                <p className="text-[10px] text-slate-600 italic">No schools saved</p>
              </div>
            )}
          </div>
        </div>

        <div className="mt-6 pt-6 border-t border-slate-800">
           <button onClick={() => { localStorage.removeItem('token'); router.push('/login'); }} className="w-full text-left px-2 text-xs text-slate-500 hover:text-red-400 transition-colors flex items-center gap-2">
             <span className="rotate-180 text-base">➔</span> Sign Out
           </button>
        </div>
      </div>

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col relative bg-[url('https://grainy-gradients.vercel.app/noise.svg')] bg-repeat">
        <div ref={scrollRef} className="flex-1 overflow-y-auto p-8 space-y-6 relative z-10">
          {messages.map((m, i) => (
            <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div className={`max-w-[75%] rounded-2xl px-5 py-3.5 shadow-xl ${
                m.role === 'user' ? 'bg-blue-600 text-white shadow-blue-900/20' : 
                m.role === 'system' ? 'bg-red-900/30 text-red-400 border border-red-800/50 text-sm' : 
                'bg-slate-900 border border-slate-800 text-slate-100'
              }`}>
                <p className="leading-relaxed whitespace-pre-wrap">{m.content}</p>
              </div>
            </div>
          ))}
          {isTyping && (
            <div className="flex items-center gap-2 text-blue-400 text-xs font-medium ml-2">
              <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-bounce"></span>
              <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-bounce [animation-delay:0.2s]"></span>
              <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-bounce [animation-delay:0.4s]"></span>
            </div>
          )}
        </div>

        <form onSubmit={onSend} className="p-6 bg-slate-900/80 backdrop-blur-xl border-t border-slate-800 relative z-20">
          <div className="flex gap-4 max-w-4xl mx-auto">
            <input className="flex-1 rounded-xl bg-slate-800 border border-slate-700 p-4 focus:ring-2 focus:ring-blue-600 outline-none transition-all placeholder:text-slate-500" placeholder="Talk to your counsellor..." value={input} onChange={(e) => setInput(e.target.value)} disabled={isTyping} />
            <button disabled={isTyping || !input.trim()} className="bg-blue-600 hover:bg-blue-500 disabled:bg-slate-700 px-8 rounded-xl font-bold transition-all shadow-lg active:scale-95 text-white">Send</button>
          </div>
        </form>
      </div>
    </div>
  );
}